---

- hosts: all
  roles:
    - common
    - dotfiles

- hosts: workstations
  roles:
    - { role: debian, when: ansible_os_family == "Debian" }
    - { role: osx, when: ansible_distribution == "MacOSX" }
    - { role: x11, when: ansible_distribution != "MacOSX" }
    - { role: xfce, when: ansible_distribution != "MacOSX" }
    - { role: i3-gaps, when: ansible_distribution != "MacOSX" }
    - R
    - vscode
    - z
