- name: install xfce4 minimal packages
  when: ansible_os_family == "Debian"
  become: yes
  apt:
    state: present
    pkg:
      - xserver-xorg
      - xfonts-base
      - task-xfce-desktop
      - gdm3

- name: restart login manager service
  when: ansible_os_family == "Debian"
  become: yes
  service: name="gdm" state="restarted"

- name: Create a directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.themes"
    state: directory
    mode: '0755'

- name: add the nordic theme for xfce
  git:
    repo: "https://github.com/EliverLara/Nordic"
    dest: "{{ ansible_env.HOME }}/.themes"
    clone: True
    force: True
    recursive: True
    update: True
    depth: 1
