---

- name: ensure dotfiles git parent path exists
  file:
    path: "{{ dotfiles_git_path | dirname }}"
    state: directory 
    mode: 0755

- name: ensure dotfiles is cloned
  git:
    repo: "{{ dotfiles_git_url }}"
    dest: "{{ dotfiles_git_path }}"
    clone: True
    recursive: True
    update: True
  notify:
    - setup dotfiles symlinks
    - setup doftiles repositories
