---

- name: set up user groups
  become: yes
  user:
    append: yes
    groups: staff
    name: '{{ansible_user_id}}'

- name: install a better shell
  become: yes
  apt: 
    name: zsh 
    state: present

- name: change shell to zsh
  become: yes
  user:
    name: '{{ansible_user_id}}'
    shell: /bin/zsh

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    clone: True
    force: True
    recursive: True
    update: True
    depth: 1

- name: add contrib and non-free
  become: yes
  apt_repository:
    state: present
    filename: nonfree
    repo: deb http://ftp.us.debian.org/debian/ buster main contrib non-free

- name: Increasing the amount of inotify watchers
  become: yes
  command: "echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p"
