---
- name: install dependencies
  become: yes
  apt:
    state: present
    pkg:
      - acl
      - bridge-utils
      - openvpn
      - libfontconfig1
      - libglib2.0-0
      - libjpeg62-turbo
      - libpixman-1-0
      - libpng16-16
      - libsdl1.2debian
      - libsm6
      - libv4l-0
      - libx11-xcb1
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxi6
      - libwebkit2gtk-4.0-37
      - cpio 
      - rpm2cpio

- name: Download Tizen IDE
  get_url:
    url: http://download.tizen.org/sdk/Installer/tizen-studio_4.1.1/web-ide_Tizen_Studio_4.1.1_ubuntu-64.bin
    dest: /tmp/tizen.bin
    mode: +x

- name: Run tizen installer
  shell: /tmp/tizen.bin
  args: 
    creates: "{{ansible_env.HOME}}/tizen-studio"
