---
  - name: ensure private key and public one are present
    copy: 
      src: "~/.ssh/{{ item }}"
      dest: "{{ansible_env.HOME}}/.ssh/{{ item }}" 
      mode: 0600
    with_items:
      - id_rsa
