---
- name: install dependencies (apt)
  become: yes
  apt:
    name:
      - apt-transport-https
    state: present

- name: Add an sbt apt key by id from a keyserver
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823

- name: install sbt repo (apt)
  become: yes
  apt_repository:
    repo: deb https://dl.bintray.com/sbt/debian /
    filename: sbt
    state: present

- name: install sbt (apt)
  become: yes
  apt:
    update_cache: yes
    name: sbt
    state: present
