---
- name: set codename
  shell: lsb_release -sc
  register: codename

- name: install key (apt)
  become: yes
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    state: present

- name: install virtualbox Code repo (apt)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{codename.stdout}} contrib
    filename: virtualbox
    state: present

- name: install virtualbox
  become: yes
  apt:
    update_cache: yes
    name: virtualbox-6.1
    state: present
