---

- name: setup dotfiles symlinks
  command: ./install_symlinks.sh
  args:
    chdir: "{{ dotfiles_git_path }}"

- name: setup dotfiles repositories
  command: ./install_repositories.sh
  args:
    chdir: "{{ dotfiles_git_path }}"
