---

- name: install key (apt)
  become: yes
  apt_key:
    url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    state: present

- name: install yarn repo (apt)
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    filename: yarn
    state: present

- name: nvm
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh
    mode: '0755'
    dest: /tmp/install_node.sh

- name: install nvm
  shell: "/tmp/install_node.sh"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: latest node
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_version }}"
  args:
    executable: /bin/bash

- name: node 10
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 10"
  args:
    executable: /bin/bash

- name: install yarn (apt)
  become: yes
  apt:
    name: yarn
    state: present
