---
- name: Install sudo
  become: yes
  become_method: su
  become_user: root
  when: ansible_os_family == "Debian"
  apt: 
    state: present
    pkg:
      - sudo

- name: Make sure we have a 'wheel' group
  become: yes
  become_method: su
  become_user: root
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  become_method: su
  become_user: root
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Add sudoers users to wheel group
  become: yes
  become_method: su
  become_user: root
  user: name=frbl groups=wheel append=yes state=present createhome=yes

- name: install essentials (Debian)
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    state: present
    pkg:
      - build-essential
      #- ansible
      - dirmngr
      - apt-transport-https
      - owncloud-client
      - figlet
      - htop
      - pandoc
      - pandoc-citeproc
      - texlive
      - texlive-full
      - latexmk 
      - tree
      - nmap
      - ctags
      - gconf2
      - poppler-utils
      - pdftk
      - myspell-nl
      - shellcheck
      - vim-nox
      - i3lock
      - libpq-dev
      - git
      #- pinta
      - rox-filer
      - python-dev
      - python3
      - python3-dev
      - python3-venv
      - lxappearance
      - rxvt-unicode-256color
      - conky
      - ranger
      - zathura
      - xsel
      - xclip
      - arandr
      - rofi
      - feh
      - compton
      - silversearcher-ag
      - tmux
      - snapd
      - libcurl4-openssl-dev
      - libxml2-dev
      - libssl-dev
      - net-tools
      - patch
      - ruby-dev
      - zlib1g-dev
      - liblzma-dev
      - chromium
      - chromium-driver
      - nfs-kernel-server
      #- signal-desktop
      #- code
      #- owncloud-client
      # - build-dep vagrant ruby-libvirt \
      # - libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev \

- name: install essentials (OSX)    
  when: ansible_distribution == "MacOSX"
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - ansible
    - cowsay
    - figlet
    - fuzzy-find
    - git
    - pwgen
    - sqlite
    - tmux
    - w3m
