---
- name: Make sure we have a 'wheel' group
  become: yes
  become_method: su
  become_user: root
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  become_method: su
  become_user: root
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Add sudoers users to wheel group
  become: yes
  become_method: su
  become_user: root
  user: name="{{user_name}}" groups=wheel append=yes state=present createhome=yes
