---
- name: Cleanup and update
  become: yes
  apt:
    update_cache: yes
    autoremove: yes
    autoclean: yes
    cache_valid_time: 3600

- name: Upgrade all packages to the latest version
  become: yes
  apt:
    force_apt_get: True
    name: "*"
    state: latest

- name: install essentials (Debian)
  become: yes
  apt:
    state: present
    pkg:
      - sshpass
      - aptitude
      - build-essential
      #- ansible
      - maven
      - curl
      - xrdp
      - dirmngr
      - apt-transport-https
      - owncloud-client
      - figlet
      - htop
      - pandoc
      - pandoc-citeproc
      - texlive
      - texlive-full
      - latexmk 
      - tree
      - nmap
      - ctags
      - gconf2
      - poppler-utils
      - pdftk
      - myspell-nl
      - shellcheck
      - vim-nox
      - i3lock
      - libpq-dev
      - git
      #- pinta
      - rox-filer
      - python-dev
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - lxappearance
      - rxvt-unicode-256color
      - conky
      - ranger
      - zathura
      - xsel
      - xclip
      - arandr
      - rofi
      - feh
      - compton
      - silversearcher-ag
      - tmux
      - snapd
      - curl
      - libcurl4-openssl-dev
      - libxml2-dev
      - libssl-dev
      - net-tools
      - patch
      - ruby-dev
      - zlib1g-dev
      - liblzma-dev
      - chromium
      - chromium-driver
      - nfs-kernel-server
      #- signal-desktop
      #- code
      #- owncloud-client
      # - build-dep vagrant ruby-libvirt \
      # - libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev \
