---
- name: Install sudo
  become: yes
  become_method: su
  become_user: root
  apt: 
    force_apt_get: True
    state: present
    pkg:
      - sudo

- name: Make sure we have a 'wheel' group
  become: yes
  become_method: su
  become_user: root
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  become_method: su
  become_user: root
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Add sudoers users to wheel group
  become: yes
  become_method: su
  become_user: root
  user: name="{{user_name}}" groups=wheel append=yes state=present createhome=yes

- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection

- name: turn on sleep
  when: ansible_os_family == "Debian"
  become: yes
  command: "systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target"

- name: ensure dirs have the correct owners
  become: true
  file:
    path: "{{ item }}"
    state: directory 
    owner: "{{ user_name }}"
    group: "wheel"
  with_items:
    - /var/lib/gems
    - /usr/local/bin
