---

- include: install_essentials.yml

- include_tasks: install_essentials_debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: install_essentials_osx.yml
  when: ansible_distribution == "MacOSX"

- include: install_ssh_keys.yml

# - include: cron_user.yml

#- include: install_runit.yml
#  when: has_root is defined
  
#- include: runit_user.yml
#  when: has_runit is defined
