---


- name: ensure i3-gaps build dependencies are installed
  become: yes
  apt:
    state: present
    pkg: 
    - curl
    - git
    - gcc
    - automake
    - make
    # https://github.com/Airblader/i3/wiki/Compiling-&-Installing#debian-stretch
    - dh-autoreconf
    - libxcb-keysyms1-dev
    - libpango1.0-dev
    - libxcb-util0-dev
    - xcb
    - libxcb1-dev
    - libxcb-icccm4-dev
    - libyajl-dev
    - libev-dev
    - libxcb-xkb-dev
    - libxcb-cursor-dev
    - libxkbcommon-dev
    - libxcb-xinerama0-dev
    - libxkbcommon-x11-dev
    - libstartup-notification0-dev
    - libxcb-randr0-dev
    - libxcb-xrm0
    - libxcb-xrm-dev
    - libxcb-shape0-dev

- name: ensure git parent path exists
  file:
    path: "{{ i3_gaps_git_path | dirname }}"
    state: directory 
    mode: 0755

- name: fetch i3-gaps latest version
  shell: |
    curl https://github.com/Airblader/i3/releases 2>/dev/null \
    | grep -E '/Airblader/i3/releases/tag/[.0-9]+' \
    | grep -Eo '[.0-9]+' \
    | sort -V \
    | tail -1
  register: i3_gaps_release_tag
  check_mode: False
  changed_when: False

- name: ensure i3-gaps is cloned
  git:
    repo: "{{ i3_gaps_git_url }}"
    dest: "{{ i3_gaps_git_path }}"
    version: "{{ i3_gaps_release_tag.stdout }}"
    clone: True
    force: True
    recursive: True
    update: True
    depth: 1
  notify:
    - autoreconf i3-gaps
    - configure i3-gaps
    - compile i3-gaps
    - install i3-gaps
